# This is a basic workflow to help you get started with Actions

name: lint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "check"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup just
        # You may pin to the exact commit or the version.
        # uses: extractions/setup-just@95b912dc5d3ed106a72907f2f9b91e76d60bdb76
        uses: extractions/setup-just@v1

      - name: Check justfile
        run: |
          just --fmt  --unstable --check

      - name: Trunk Check and Upload
        # You may pin to the exact commit or the version.
        # uses: trunk-io/trunk-action@22e948f7bb9f870bc6c42625585f1ef27e9c5afc
        uses: trunk-io/trunk-action@v1.0.4
        with:
          # Path to Trunk Launcher. If not provided, we'll look for it the repo root, `.trunk/bin` and `tools/`. If it can't be found anywhere and is not provided explicitly, we'll download it on demand.
          #trunk-path: # optional
          # Label to append to the check run name (useful if running Trunk Check on multiple platforms)
          # Extra arguments to pass to trunk
          arguments: --github-annotate-new-only=false --github-label=${{ runner.os }} # optional
          # Trunk check mode. Leave unset to autodetect just changes. Set to 'all' to check the entire repository. If `trunk-token` is set with 'all', 'all' will also upload results to the Trunk web app.
          check-mode: all # optional
          # Cache trunk downloads and results between runs. Caching is only needed when using ephemeral CI runners.
          cache: false # optional, default is true
          # You can find a per-repo API token in the Trunk web app settings. This will cause results to be uploaded to the Trunk web app if this job is a scheduled job running on a branch, or if `check-mode` is set to 'all'.
          trunk-token: ${{ secrets.TRUNK_TOKEN }} # optional
          # Upload series name, for when `trunk-token` is provided. If not provided, we'll use the branch name.
          upload-series: main # optional

