name: Nightly
on:
  schedule:
    - cron: 0 8 * * 1-5
  workflow_dispatch: {}

jobs:
  trunk_check:
    name: Trunk Check Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trunk Check
        uses: ./ # external users, use: trunk-io/trunk-action@v1
        with:
          # Path to Trunk Launcher. If not provided, we'll look for it the repo root, `.trunk/bin` and `tools/`. If it can't be found anywhere and is not provided explicitly, we'll download it on demand.
          #trunk-path: # optional
          # Label to append to the check run name (useful if running Trunk Check on multiple platforms)
          # Extra arguments to pass to trunk
          arguments: --github-annotate-new-only=false --github-label=${{ runner.os }} # optional
          # Trunk check mode. Leave unset to autodetect just changes. Set to 'all' to check the entire repository. If `trunk-token` is set with 'all', 'all' will also upload results to the Trunk web app.
          check-mode: all # optional
          # Cache trunk downloads and results between runs. Caching is only needed when using ephemeral CI runners.
          cache: false # optional, default is true
          # You can find a per-repo API token in the Trunk web app settings. This will cause results to be uploaded to the Trunk web app if this job is a scheduled job running on a branch, or if `check-mode` is set to 'all'.
          trunk-token: ${{ secrets.TRUNK_TOKEN }} # optional
          # Upload series name, for when `trunk-token` is provided. If not provided, we'll use the branch name.
          upload-series: main # optional
